[package]
name = "program-verify"
version = "0.1.3"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
clap = { version = "4", features = ["derive"] }
jsonschema = "0.17"
regex = "1"
